sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lz0048768
  redis:
    host:localhost
    port:6379
    password:123456
    database:0
  wechat:
    appid: wxe273def3406d0577
    secret: f090ebd51ee57ece9f206845d68942de
